lq45 = [
"Aneka Tambang Persero",
"Media Nusantara Citra", 
"Telkom Indonesia", 
"Erajaya Swasembada", 
"Merdeka Copper Gold TBK PT",
"Sarana Menara Nusantara",
"Bank Rakyat Persero",
"Adaro Energy",
"Tower Bersama",
"Medco Energi",
"Mitra Keluarga Karyasehat",
"Perusahaan Gas Negara",
"Vale Indonesia",
"Unilever Indonesia",
"Bank Mandiri Persero",
"Astra International",
"Japfa Comfeed Indonesia",
"Hm Sampoerna",
"Bank Tabungan Negara",
"Kalbe Farma",
"Summarecon Agung",
"Pp Persero",
"Bank Negar",
"Pakuwon Jati",
"Bukit Asam",
"Ace Hardware",
"XL Axiata",
"Bank Central Asia",
"Wijaya Karya",
"Bumi Serpong Damai",
"Ciputra Dev",
"Akr Corporindo",
"Semen Indonesia Persero",
"Indah Kiat Pulp & Paper",
"Charoen Pokphand Indonesia",
"United Tractors",
"Jasa Marga",
"Pabrik Kertas Tjiwi",
"Indofood",
"Bank Tabungan Pensiunan",
"Indofood Cbp",
"Indocement Tunggal",
"Gudang Garam",
"Indo Tambangraya",
"Chandra Asri Petro"
]